// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"PlayMusic","alias":"$LATEST","description":"","bot-template":"bot-import","commands-help":[],"region":"us-east-1"}],
    'aws_cognito_identity_pool_id': 'us-east-1:dafa168d-1d9e-4fd2-acc9-a159764f9257',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reactchatbot-hosting-mobilehub-1519872555',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3ukw425uaqw3w.cloudfront.net',
    'aws_mobile_analytics_app_id': 'ff6a3c1cd2254c82a23a9d2f9c254d86',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e6646ae5-21b1-4ba1-97ef-7163578c867e',
    'aws_project_name': 'react-chatbot-2019-11-09-15-17-10',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'reactchatbot-mobilehub-1519872555',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_HrOeOa4P7',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6luisfrbeqnlfp4serio1rhe7a',
}

export default awsmobile;
