#!/bin/sh
    echo "Running deployment script"
    ssh ubuntu@172.31.5.65 << EOF
    pwd
    whoami
    echo "after git pull code 2"
    cd ~/Cloud-Project-2
    echo "after git pull code 3"
    sudo git pull origin master
    echo "after git pull code 4"
    sudo npm install
    #sudo npm install -g nodemon pm2
    sudo pm2 restart ecosystem.config.js
    exit

    EOF